spring:
  profiles:
    active: dev

# 数据库配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/customer
    username: root
    password: tigerwith
# 存储层JPA配置
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

# Mybatis配置
mybatis:
  # 配置映射类所在包名
  type-aliases-package: com.zmj.demo.domain
  mapper-locations: classpath*:**/mapper/*.xml
  # 配置mapper xml文件所在路径，这里是一个数组
# mybatis.config：mybatis-config.xml配置文件的路径
# mybatis.typeHandlersPackage：扫描typeHandlers的包
# mybatis.checkConfigLocation：检查配置文件是否存在
# mybatis.executorType：设置执行模式（SIMPLE, REUSE, BATCH），默认为SIMPLE