spring:
  profiles:
    active: dev

# 数据库配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/customer
    username: root
    password: tigerwith
    tomcat:
      max-active: 10
      max-idle: 5
      min-idle: 0
# 存储层JPA配置
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  # redis配置
  redis:
    # redis数据库索引（默认为0），我们使用索引为3的数据库，避免和其他数据冲突
    database: 3
    # redis服务器地址（默认为localhost)
    host: localhost
    # redis端口
    # redis访问密码（默认为空）
    password:
    # redis连接超时时间（单位为毫秒)
    timeout: 0
    # redis连接池配置
    pool:
      # 最大可用连接数（默认为8，负数表示无限)
      max-active: 8
      # 最大空闲连接数（默认为8，负数表示无限）
      max-idle: 8
      # 最小空闲连接数（默认为0，该值只有为正数才有作用）
      min-idle: 0
      # 从连接池中获取连接最大等待时间（默认为-1，单位为毫秒，负数表示无限）
      max-wait: -1

# Mybatis配置
mybatis:
  # 配置映射类所在包名
  type-aliases-package: com.zmj.demo.domain
  mapper-locations: classpath:/mapper/*.xml
  # 设置配置文件路径
  config-location: classpath:mybatis-config.xml

  # 配置mapper xml文件所在路径，这里是一个数组
# mybatis.config：mybatis-config.xml配置文件的路径
# mybatis.typeHandlersPackage：扫描typeHandlers的包
# mybatis.checkConfigLocation：检查配置文件是否存在
# mybatis.executorType：设置执行模式（SIMPLE, REUSE, BATCH），默认为SIMPLE